- title: "Private Training"
  title_detail: "Lash Extension - Private Training"
  slug: "/private"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "private"
  cover: "./private/trainings-private-001.jpg"
  desc: "1 on 1 training that focuses completely on YOU! With the educator?s full attention on you, the training is completely customized and catered to your needs, by assessing your skills and focusing on areas of improvement from lashing skills to business strategies that will help spike your business!"
  price_line1: ""
  price_line2: ""
- title: "Group Training"
  title_detail: "Lash Extension - Group Training"
  slug: "/group"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "group"
  cover: "./group/trainings-group-001.jpg"
  desc: "Small Group Training is a  ratio of 4 students to one educator, focusing on the general criteria and foundation of lashing such as sanitization, disinfection, safe application, styling, branding and more!"
  price_line1: ""
  price_line2: ""
- title: "Classic Advanced Training"
  title_detail: "Classic Lash Extension - Advanced Training"
  slug: "/cadvanced"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "cadvanced"
  cover: "./cadvanced/trainings-cadvanced-001.jpg"
  desc: "Course Includes:<br/>+1 Nixlash Classic Kit<br/>Kit Includes:<br/>+Mixed Classic Trays (covers up to 60+ clients)<br/>+Glue Rings<br/>+Nano Mister<br/>+2 Tweezers<br/>+Lash Wands<br/>+1 Lash Tile<br/>+Lash Remover<br/>+Nexcare Tape<br/>+Lash Glue<br/>+Micro Brushes<br/>+Practice Lashes<br/>+Travel Box"
  price_line1: "<b>$1000"
  price_line2: ""
- title: "Classic / Intro to Volume Training"
  title_detail: "Classic / Intro to Volume Lash Extension Training"
  slug: "/cintrovol"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "cintrovol"
  cover: "./cintrovol/trainings-cintrovol-001.jpg"
  desc: "Course Includes:<br/>+1 Nixlash Classic/Volume Kit<br/>Kit Includes:<br/>+Mixed Classic and Volume Trays (covers up to 60+ clients)<br/>+Glue Rings<br/>+Nano Mister<br/>+3 Tweezers<br/>+Lash Wands<br/>+1 Lash Tile<br/>+Lash Remover<br/>+Nexcare Tape<br/>+Lash Glue<br/>+Micro Brushes<br/>+Practice Lashes
  +Travel Box"
  price_line1: "<b>$1200"
  price_line2: ""
- title: "Volume / Mega Volume Advanced Training"
  title_detail: "Volume / Mega Volume Lash Extension - Advanced Training"
  slug: "/mvadvanced"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "mvadvanced"
  cover: "./mvadvanced/trainings-mvadvanced-001.jpg"
  desc: "Course Includes:<br/>+1 Nixlash Volume/Mega Volume Kit<br/>+Complimentary Classic Refresher<br/>Kit Includes:<br/>+Mixed Volume and Mega Volume Trays (covers up to 60+ clients)<br/>+Glue Rings<br/>+Nano Mister<br/>+2 Tweezers<br/>+Lash Wands<br/>+1 Lash Tile<br/>+Lash Remover<br/>+Nexcare Tape<br/>+Lash Glue<br/>+Micro Brushes<br/>+Practice Lashes<br/>+Travel Box"
  price_line1: "<b>$1000"
  price_line2: ""
- title: "Refresher Classes"
  title_detail: "Refresher Classes"
  slug: "/refresher"
  category: "NIXLASH Academy"
  color: "#ffcccc"
  images: "refresher"
  cover: "./refresher/trainings-refresher-001.jpg"
  desc: "If you have already attained a certification but would like to tweak your lashing skills and revise your business plan, refresher classes are perfect for refining your skills and building confidence as a lash artist"
  price_line1: "<b>Classic Refresher $500"
  price_line2: "<b>Volume Refresher $500"
