- name: "Services"
  link: "/projects"
- name: "Academy"
  link: "/trainings"
- name: "Insta"
  link: "/instagram"
- name: "FAQ"
  link: "/faq"
- name: "About"
  link: "/about"
- name: "Policy"
  link: "/policy"